import { Geist, Geist_Mono } from "next/font/google";
import SidePanelAdmin from "@/components/admin/SidePanelAdmin";
import "@/app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Admin Dashboard",
  description: "Generated by create next app",
};


export default function Admin({children}){
    return(
        
        <html
        lang="en"
        className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
        >
        <body className="min-h-full flex flex-col">
            <h1>This is a navbar for admin</h1>
            <div className="flex flex-row">
              <SidePanelAdmin />
              {children}
            </div>
        </body>
        </html>
    );
}